development:
  adapter: postgresql
  database: suit_shop_development

test: &test
  adapter: postgresql
  database: suit_shop_test

production:
  adapter: postgresql
  database: suit_shop_production

cucumber:
  <<: *test
